#ifndef DATATYPENAMES_H
#define DATATYPENAMES_H

#define MPH "mph"
#define KPH "kph"
#define STATUS "status"
#define DIRECTION "direction"
#define PACKTEMP "packtemp"
#define MOTORTEMP "motortemp"
#define STATEOFCHARGE "stateofcharge"
#define CURRENT "current"
#define BALANCINGCELLS "balancingcells"
#define PACKVOLTAGE "packvoltage"
#define MAXCELLTEMP "maxcelltemp"
#define MAXCELLTEMPCHIP "maxcelltempchip"
#define MAXCELLTEMPCELL "maxcelltempcell"
#define MAXCELLVOLTAGE "maxcellvoltage"
#define MAXCELLVOLTAGECHIP "maxcellvoltagechip"
#define MAXCELLVOLTAGECELL "maxcellvoltagecell"
#define MINCELLTEMP "mincelltemp"
#define MINCELLTEMPCHIP "mincelltempchip"
#define MINCELLTEMPCELL "mincelltempcell"
#define MINCELLVOLTAGE "mincellvoltage"
#define MINCELLVOLTAGECHIP "mincellvoltagechip"
#define MINCELLVOLTAGECELL "mincellvoltagecell"
#define AVECELLTEMP "avecelltemp"
#define AVECELLVOLTAGE "avecellvoltage"
#define CELLVOLTAGEDELTA "cellvoltagedelta"
#define BURNINGCELLS "burningcells"
#define TRACTIONCONTROL "tractioncontrol"
#define INVERTERTEMP "invertertemp"
#define MOTORPOWER "motorpower"
#define FANPOWER "fanpower"
#define REGENPOWER "regenpower"
#define BMSSTATE "bmsstate"
#define BMSFAULT "bmsfault"
#define MPUFAULT "mpufault"
#define DCL "dcl"
#define CCL "ccl"
#define FORWARDBUTTON "forwardbutton"
#define BACKWARDBUTTON "backwardbutton"
#define RIGHTBUTTON "rightbutton"
#define ENTERBUTTON "rightbutton"
#define UPBUTTON "upbutton"
#define DOWNBUTTON "downbutton"
#define MODEINDEX "modeindex"
#define GFORCEX "gforcex"
#define GFORCEY "gforcey"
#define GFORCEZ "gforcez"
#define SEGMENTTEMP1 "segmenttemp1"
#define SEGMENTTEMP2 "segmenttemp2"
#define SEGMENTTEMP3 "segmenttemp3"
#define SEGMENTTEMP4 "segmenttemp4"
#define TORQUEPOWER "torquepower"
#define SIDEBRBS "SIDEBRBS"
#define BMS "BMS"
#define BSPD "BSPD"
#define MPU "MPU"
#define BOTS "BOTS"
#define INERTIA "INERTIA"
#define CPBRB "CP BRB"
#define TSMS "TSMS"
#define HVDINTRLK "HVD INTRLK"
#define HVCNCTR "HV CNCTR"

#endif // DATATYPENAMES_H
