#ifndef DATATYPENAMES_H
#define DATATYPENAMES_H

#define MPH "mc/speed/mph"
#define KPH "mc/speed/kph"
#define STATUS "status"
#define DIRECTION "direction"
#define PACKTEMP "bms/temps/packtemp"
#define MOTORTEMP "bms/temps/motortemp"
#define STATEOFCHARGE "BMS/Pack/SOC"
#define CURRENT "current"
#define BALANCINGCELLS "balancingcells"
#define PACKVOLTAGE "packvoltage"
#define MAXCELLTEMP "maxcelltemp"
#define MAXCELLTEMPCHIP "maxcelltempchip"
#define MAXCELLTEMPCELL "maxcelltempcell"
#define MAXCELLVOLTAGE "maxcellvoltage"
#define MAXCELLVOLTAGECHIP "maxcellvoltagechip"
#define MAXCELLVOLTAGECELL "maxcellvoltagecell"
#define MINCELLTEMP "mincelltemp"
#define MINCELLTEMPCHIP "mincelltempchip"
#define MINCELLTEMPCELL "mincelltempcell"
#define MINCELLVOLTAGE "mincellvoltage"
#define MINCELLVOLTAGECHIP "mincellvoltagechip"
#define MINCELLVOLTAGECELL "mincellvoltagecell"
#define AVECELLTEMP "avecelltemp"
#define AVECELLVOLTAGE "avecellvoltage"
#define CELLVOLTAGEDELTA "cellvoltagedelta"
#define BURNINGCELLS "burningcells"
#define TRACTIONCONTROL "tractioncontrol"
#define INVERTERTEMP "invertertemp"
#define MOTORPOWER "motorpower"
#define FANPOWER "fanpower"
#define REGENPOWER "regenpower"
#define BMSSTATE "bmsstate"
#define BMSFAULT "bmsfault"
#define MPUFAULT "mpufault"
#define DCL "dcl"
#define CCL "ccl"
#define FORWARDBUTTON "WHEEL/Buttons/1"
#define BACKWARDBUTTON "WHEEL/Buttons/1"
#define RIGHTBUTTON "WHEEL/Buttons/1"
#define ENTERBUTTON "WHEEL/Buttons/1"
#define UPBUTTON "WHEEL/Buttons/1"
#define DOWNBUTTON "WHEEL/Buttons/1"
#define HOMEBUTTON "MPU/State/Mode"
#define MODEINDEX "MPU/State/ModeIndex"
#define GFORCEX "gforcex"
#define GFORCEY "gforcey"
#define GFORCEZ "gforcez"
#define SEGMENTTEMP1 "segmenttemp1"
#define SEGMENTTEMP2 "segmenttemp2"
#define SEGMENTTEMP3 "segmenttemp3"
#define SEGMENTTEMP4 "segmenttemp4"
#define TORQUEPOWER "torquepower"
#define SIDEBRBS "SIDEBRBS"
#define BMS "BMS"
#define BSPD "BSPD"
#define MPU "MPU"
#define BOTS "BOTS"
#define INERTIA "INERTIA"
#define CPBRB "CP BRB"
#define TSMS "TSMS"
#define HVDINTRLK "HVD INTRLK"
#define HVCNCTR "HV CNCTR"
#define CRITICALFAULTS "CRITICAL FAULTS"
#define NONCRITICALFAULTS "NON CRITICAL FAULTS"
#define MICROPHONE "MICROPHONE"
#define FASTESTTIME "FASTESTTIME"
#define LASTTIME "LASTTIME"
#define CURRENT_TIME "CURRENT_TIME"

#endif // DATATYPENAMES_H
