#ifndef DATATYPENAMES_H
#define DATATYPENAMES_H

#define MPH "MPU/State/Speed"
#define KPH "mc/speed/kph"
#define STATUS "status"
#define DIRECTION "direction"
#define PACKTEMP "BMS/Status/Temp_Average"
#define MOTORTEMP "DTI/Temps/Motor_Temperature"
#define STATEOFCHARGE "BMS/Pack/SOC"
#define CURRENT "DTI/Power/AC_Current"
#define BALANCINGCELLS "balancingcells"
#define PACKVOLTAGE "BMS/Pack/Voltage"
#define MAXCELLTEMP "BMS/Cells/Temp_High_Value"
#define MAXCELLTEMPCHIP "BMS/Cells/Temp_High_Chip"
#define MAXCELLTEMPCELL "BMS/Cells/Temp_High_Cell"
#define MAXCELLVOLTAGE "BMS/Cells/Volts_High_Value"
#define MAXCELLVOLTAGECHIP "BMS/Cells/Volts_High_Chip"
#define MAXCELLVOLTAGECELL "BMS/Cells/Volts_High_Cell"
#define MINCELLTEMP "BMS/Cells/Temp_Low_Value"
#define MINCELLTEMPCHIP "BMS/Cells/Temp_Low_Chip"
#define MINCELLTEMPCELL "BMS/Cells/Temp_Low_Cell"
#define MINCELLVOLTAGE "BMS/Cells/Volts_Low_Value"
#define MINCELLVOLTAGECHIP "BMS/Cells/Volts_Low_Chip"
#define MINCELLVOLTAGECELL "BMS/Cells/Volts_Low_Cell"
#define AVECELLTEMP "BMS/Status/Temp_Average"
#define AVECELLVOLTAGE "BMS/Status/Voltage_Average"
#define CELLVOLTAGEDELTA "cellvoltagedelta"
#define BURNINGCELLS "burningcells"
#define TRACTIONCONTROL "tractioncontrol"
#define INVERTERTEMP "invertertemp"
#define MOTORPOWER "motorpower"
#define FANPOWER "fanpower"
#define REGENPOWER "regenpower"
#define BMSSTATE "bmsstate"
#define BMSFAULT "BMS/Status/Faults"
#define MPUFAULT "mpufault"
#define DCL "BMS/Pack/DCL"
#define CCL "BMS/Pack/CCL"
#define FORWARDBUTTON "WHEEL/Buttons/1"
#define BACKWARDBUTTON "WHEEL/Buttons/1"
#define RIGHTBUTTON "WHEEL/Buttons/1"
#define ENTERBUTTON "WHEEL/Buttons/1"
#define UPBUTTON "WHEEL/Buttons/1"
#define DOWNBUTTON "WHEEL/Buttons/1"
#define HOMEBUTTON "MPU/State/Mode"
#define MODEINDEX "MPU/State/ModeIndex"
#define GFORCEX "gforcex"
#define GFORCEY "gforcey"
#define GFORCEZ "gforcez"
#define SEGMENTTEMP1 "segmenttemp1"
#define SEGMENTTEMP2 "segmenttemp2"
#define SEGMENTTEMP3 "segmenttemp3"
#define SEGMENTTEMP4 "segmenttemp4"
#define TORQUEPOWER "torquepower"
#define SIDEBRBS "SIDEBRBS"
#define BMS "BMS"
#define BSPD "BSPD"
#define MPU "MPU"
#define BOTS "BOTS"
#define INERTIA "INERTIA"
#define CPBRB "CP BRB"
#define TSMS "TSMS"
#define HVDINTRLK "HVD INTRLK"
#define HVCNCTR "HV CNCTR"
#define CRITICALFAULTS "BMS/Status/Faults"
#define NONCRITICALFAULTS "BMS/Status/Faults"
#define MICROPHONE "MICROPHONE"
#define FASTESTTIME "FASTESTTIME"
#define LASTTIME "LASTTIME"
#define CURRENT_TIME "CURRENT_TIME"
#define LOWVOLTAGESOC "LOWVOLTAGESOC"

#endif // DATATYPENAMES_H
