name: Build and Test

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Qt (if not already installed)
          run: |
            sudo apt-get install qt6-default 

      - name: Build Application
        run: |
          qmake
          make